### ISSUE TITLE
Remove Max and his related work

### ISSUE THREAD

**Issue by tinedpakgamer** [wavEye-Project/BEAMinject#1]
You are no longer allowed to use work of max and hence you must remove it from your repositories
![image](https://github.com/user-attachments/assets/2802c472-92d8-4ef1-9705-c0b10b5c43e2)
![image](https://github.com/user-attachments/assets/df8d1cc4-0a14-4235-8e41-77bf69fde134)

**Comment by run4r-ses** [comment]
Fixed with https://github.com/wavEye-Project/BEAMinject/commit/a3785d86a8846c5efc8ebf5bd0798ca8686f0911.
